FROM oven/bun:slim

WORKDIR /app

# Copy package files first for better caching
COPY server/dist/app.js ./
COPY server/.env ./
# Expose the port your server runs on
EXPOSE 3000

# Start the server
CMD ["bun", "run", "app.js"]
