name: Build Tauri Frontend

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build frontend on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libwebkit2gtk-4.1-dev \
            patchelf

      - name: Install Windows build dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y nsis
        shell: powershell

      - name: Install frontend dependencies
        working-directory: client
        run: bun install --frozen-lockfile

      - name: Build Tauri app
        working-directory: client
        run: bunx --bun tauri build

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle-${{ matrix.os }}
          path: client/src-tauri/target/release/bundle
          if-no-files-found: error
