name: Vercel Push Deploy
on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel

      - name: Deploy client
        working-directory: ./client
        run: vercel --prod --token=$VERCEL_TOKEN --yes --confirm
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_CLIENT_PROJECT_ID }}

      - name: Deploy server
        working-directory: ./server
        run: vercel --prod --token=$VERCEL_TOKEN --yes --confirm
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}
